---
#####
# https://github.com/probot/settings#usage
# _extends: 'github'
repository:
  name: github
  topics: 'cloud, devops, sre, github, actions, templates, probot'
  description: 'GitHub Automation > actions / templates / probot configurations > automated with GitHub actions'
  homepage: 'https://github.com/npm'
  default_branch: master
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  has_downloads: true
  has_issues: true
  has_projects: true
  has_wiki: false
  private: true

branches:
  - name: master
    protection:
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
        dismissal_restrictions:
          teams: []
          users: []
      required_status_checks:
        strict: true
        contexts: ['default']
      restrictions:
        teams: []
        users: []

teams:
  - name: sre
    permission: admin
  - name: robot-write
    permission: push
  - name: robot
    permission: pull

labels:

  - color: '80C000' # Green
    description: ''
    name: feature
  - color: 'FF8000' # Orange
    description: ''
    name: refactor
  - color: 'C00000' # Red
    description: ''
    name: bug
  - color: 'FFC000' # Yellow
    description: ''
    name: chore
  - color: '00C0FF' # Light Blue
    description: ''
    name: ci
  - color: '4080FF' # Blue
    description: ''
    name: cd
  - color: 'C080FF' # Light Purple
    description: ''
    name: docs

  - color: '000000' # Black
    description: ''
    name: question
  - color: '999999' # Gray
    description: ''
    name: duplicate
  - color: '999999' # Gray
    description: ''
    name: invalid
  - color: '999999' # Gray
    description: ''
    name: wontfix
